#using conditions in ansible playbook
# #conditions are used to execute tasks based on certain conditions
- name: conditions
  hosts: localhost
  become: true  #become is used to run the task as a different user, in this case, root user
  tasks: 
  - name: check if user roboshop is exist or not
    ansible.builtin.user:
      name: roboshop
      state: present
    register: user_check  #register is used to store the output of the task in a variable

  - name: create user
    ansible.builtin.user:
      name: roboshop
      state: present
    when: user_check is failed  #when is used to execute the task only if the condition is true  
