#using conditions in ansible playbook
# #conditions are used to execute tasks based on certain conditions
- name: conditions
  hosts: localhost
  become: true  #become is used to run the task as a different user, in this case, root user
  tasks: 
  - name: check if user balaji exist or not
    ansible.builtin.command: id balaji  #command module is used to run a command on the remote host
    ignore_errors: true  #ignore_errors is used to ignore the error if the command fails,
    register: user_check  #register is used to store the output of the command in a variable called user_check

  - name: print variable user_check output
    ansible.builtin.debug:
      msg: "User check output is {{user_check}}"  #stdout is used to get the output of the command

  - name: print exit status or return code
    ansible.builtin.debug:                      #0 means success and non-zero means failure    
      msg: "return code is {{user_check.rc}}"  #rc is used to get the return code of the command

  - name: create user if not exist #create user task
    ansible.builtin.user:
      name: balaji
    when: user_check.rc !=0  #when is used to execute the task only if the condition is true  

