#we are wrtiing multi playbook
#multi playbook is a playbook which contains multiple plays
#we can have multiple plays in a playbook 
#playbook always start with - dash

- name: playbook-1
  hosts: localhost
  tasks:
  - name: play-1 from task-1
    ansible.builtin.debug:
      msg: "hello from playbook1"

- name: playbook-2
  hosts: web
  tasks:
  - name: play-2 from task-2 
    ansible.builtin.debug:
      msg: "hello from playbook2"
