#we are trying to install nginx in this playbook

- name: nginx playbook
  become: true
  hosts: web
  tasks: 
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx  
    ansible.builtin.service:
      name: nginx
      state: started  